modified wf-1.yaml v2

diff --git a/.github/workflows/wf-1.yaml b/.github/workflows/wf-1.yaml
--- a/.github/workflows/wf-1.yaml
+++ b/.github/workflows/wf-1.yaml
@@ -7,11 +7,20 @@ jobs:
     steps:
       - name: Step 1
         run: echo "This is job 1, step 1"
+      - name: Step 2
+        run: echo "This is job 1, step 2"
   job_2:
     runs-on: ubuntu-latest
-    # needs: job_1
+    steps:
+      - name: fail-step
+        run: |
+          echo "step going to fail!"
+          exit 1
+      - name: error message
+        run: echo "failed!"
+  job_3:
+    runs-on: ubuntu-latest
+    needs: job_2
     steps:
       - name: Step 1
-        run: echo "This is job 2, step 1"
-      - name: Step 2
-        run: echo "This is job 2, step 2"
+        run: echo "This is job 3, step 1"
